# Site settings
title: Damn Good Stuff
description: > # this means to ignore newlines until "baseurl:"
  God looked over everything he had made.
  "It was so good, so damn good!"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://josephishere.github.io" # the base hostname & protocol for your site

# Build settings
markdown: rdiscount
